#!/usr/bin/env python3
"""Generate cw_env_rom.v, the raised cosine CW envelope table.

radio.sv indexes the ROM with tx_cwlevel[18:11]. tx_cwlevel ramps between 0 and
MAX_CWLEVEL (0x4d800), so the index only reaches MAX_CWLEVEL >> 11 = 155: the
whole sin^2 rise is placed on indexes 0..155, and 156..255 (never used) hold
the peak. The peak is 0x4d80, the maximum of the linear ramp
(tx_cwlevel[18:4]), which keeps the CORDIC below full scale.

Usage: python3 cw_env_rom.py > cw_env_rom.v
"""
import math

MAX_CWLEVEL = 0x4D800
LAST = MAX_CWLEVEL >> 11      # 155
PEAK = MAX_CWLEVEL >> 4       # 0x4d80


def value(i):
    if i >= LAST:
        return PEAK
    return int(round(PEAK * math.sin(0.5 * math.pi * i / LAST) ** 2))


def main():
    print("// Raised cosine (sin^2) CW envelope, generated by cw_env_rom.py")
    print("// Index tx_cwlevel[18:11] runs 0..%d (MAX_CWLEVEL 0x%x); peak 0x%04x" % (LAST, MAX_CWLEVEL, PEAK))
    print("module cw_env_rom (")
    print("  input  [7:0]  addr,")
    print("  output [15:0] data")
    print(");")
    print("")
    print("  reg [15:0] rom [255:0];")
    print("")
    print("  initial begin")
    for i in range(256):
        print("    rom[%d]%s = 16'h%04X;" % (i, " " * (4 - len(str(i))), value(i)))
    print("  end")
    print("")
    print("  assign data = rom[addr];")
    print("")
    print("endmodule")


if __name__ == "__main__":
    main()
